apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nzsd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-nzsd@sha256:fddf0518cd8812d4d05e6bd021042234ad14980dff1f0fc4e3037698d593b7ca
        name: my-nodejs
        resources: {}
status: {}
